### ISSUE TITLE
Add Kubernetes deployment manifests

### ISSUE THREAD

**Issue by eagurin** [eagurin/cynosure#18]
## Summary
Create Kubernetes manifests and Helm charts for production deployment of Cynosure Bridge.

## Description
Enable easy deployment to Kubernetes clusters with proper configuration management, scaling, and monitoring.

### Kubernetes Resources
- [ ] Deployment manifest
- [ ] Service configuration
- [ ] ConfigMap for environment variables
- [ ] Secret for sensitive data
- [ ] Ingress for external access
- [ ] HorizontalPodAutoscaler
- [ ] PodDisruptionBudget
- [ ] NetworkPolicy
- [ ] ServiceMonitor (for Prometheus)

### Helm Chart
- [ ] Chart.yaml with metadata
- [ ] Values.yaml with configuration
- [ ] Templates for all K8s resources
- [ ] Helper templates
- [ ] NOTES.txt for deployment instructions

### Configuration
```yaml
# values.yaml example
replicaCount: 3

image:
  repository: cynosure
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.cynosure.example.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
```

### Security
- [ ] Pod security contexts
- [ ] Resource limits and requests
- [ ] Network policies
- [ ] RBAC configuration
- [ ] Image security scanning

### Monitoring
- [ ] Liveness and readiness probes
- [ ] Prometheus metrics scraping
- [ ] Grafana dashboard
- [ ] Alert rules

## Implementation Plan
1. Create basic Kubernetes manifests
2. Develop Helm chart structure
3. Add configuration templates
4. Implement security best practices
5. Add monitoring and observability
6. Create deployment documentation
7. Test in staging environment

## Priority
Medium - Important for production readiness
