### ISSUE TITLE
Add Prometheus metrics and monitoring

### ISSUE THREAD

**Issue by eagurin** [eagurin/cynosure#19]
## Summary
Implement Prometheus metrics export for monitoring and observability of Cynosure Bridge.

## Description
Add comprehensive metrics collection to monitor:
- API performance and usage
- Claude client behavior
- System health and resources
- Business metrics

### HTTP Metrics
- [ ] Request count by endpoint and method
- [ ] Response time histograms
- [ ] Error rate by status code
- [ ] Active connections
- [ ] Request size and response size

### Application Metrics
- [ ] Claude API calls (success/failure)
- [ ] Translation processing time
- [ ] Streaming connection count
- [ ] Cache hit/miss ratios
- [ ] Queue lengths and processing times

### System Metrics
- [ ] Memory usage
- [ ] CPU utilization
- [ ] Garbage collection metrics
- [ ] Event loop lag

### Business Metrics
- [ ] API key usage per client
- [ ] Model usage distribution
- [ ] Cost tracking
- [ ] Token consumption

### Metrics Library
```typescript
import { register, Counter, Histogram, Gauge } from 'prom-client';

// HTTP metrics
const httpRequestsTotal = new Counter({
  name: 'http_requests_total',
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'route', 'status_code']
});

const httpRequestDuration = new Histogram({
  name: 'http_request_duration_seconds',
  help: 'HTTP request duration in seconds',
  labelNames: ['method', 'route']
});

// Claude metrics
const claudeApiCalls = new Counter({
  name: 'claude_api_calls_total',
  help: 'Total Claude API calls',
  labelNames: ['model', 'status']
});
```

### Endpoints
- [ ] `/metrics` - Prometheus metrics endpoint
- [ ] `/health/metrics` - Health check with metrics
- [ ] Custom metrics dashboard

### Alerting Rules
```yaml
groups:
  - name: cynosure-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected

      - alert: ClaudeAPIDown
        expr: rate(claude_api_calls_total{status="error"}[5m]) > 0.5
        for: 2m
        labels:
          severity: critical
```

### Grafana Dashboard
- [ ] API performance overview
- [ ] Claude integration status
- [ ] Error tracking
- [ ] Resource utilization
- [ ] Business metrics

## Priority
High - Essential for production monitoring
